# Generated by Django 2.2.24 on 2023-05-17 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(
                related_name='liked_flats',
                related_query_name='who_likes',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кто лайкнул',
            ),
        ),
    ]
